'use client';
import { useState } from 'react'; import { decodeEventLog } from 'viem'; import { useAccount,usePublicClient,useWalletClient } from 'wagmi';
import NextActionHint from '@/components/common/NextActionHint'; import { sepoliaDeployment } from '@/lib/api/generated/sepolia-deployment';
export const SLICE3_TEST_TOKEN={name:'Meraki Slice 3 Test Asset',symbol:'MS3T',maxSupply:BigInt('1000000000000000000000000'),basePrice:BigInt('1000000000000'),priceSlope:BigInt('1000'),metadataURI:'data:application/json,{"name":"Meraki Slice 3 Test Asset","description":"Sepolia-only Meraki Slice 3 controlled test asset. No value or production claims."}'} as const;
const registryAbi=[{type:'function',name:'registerLaunchMetadata',stateMutability:'nonpayable',inputs:[{type:'string'},{type:'string'},{type:'uint256'},{type:'uint256'},{type:'uint256'},{type:'string'}],outputs:[{type:'uint256'}]},{type:'event',name:'LaunchMetadataRegistered',inputs:[{name:'configId',type:'uint256',indexed:true},{name:'creator',type:'address',indexed:true}]}] as const;
const factoryAbi=[{type:'function',name:'launchFee',stateMutability:'view',inputs:[],outputs:[{type:'uint256'}]},{type:'function',name:'createLaunch',stateMutability:'payable',inputs:[{type:'uint256'}],outputs:[{type:'address'}]}] as const;
export default function LaunchForm(){const {address,isConnected,chainId}=useAccount();const {data:wallet}=useWalletClient();const client=usePublicClient();const [status,setStatus]=useState('Ready for controlled Sepolia creation');const [busy,setBusy]=useState(false);const registry=sepoliaDeployment.contracts.launchRegistry.address;const factory=sepoliaDeployment.contracts.launchFactory.address;
async function create(){if(!wallet||!client||!address||chainId!==11155111)return;setBusy(true);try{setStatus('Simulating metadata registration');const args=[SLICE3_TEST_TOKEN.name,SLICE3_TEST_TOKEN.symbol,SLICE3_TEST_TOKEN.maxSupply,SLICE3_TEST_TOKEN.basePrice,SLICE3_TEST_TOKEN.priceSlope,SLICE3_TEST_TOKEN.metadataURI] as const;const sim1=await client.simulateContract({account:address,address:registry,abi:registryAbi,functionName:'registerLaunchMetadata',args});setStatus('Approve metadata registration in wallet (transaction 1 of 2)');const hash1=await wallet.writeContract(sim1.request);const receipt1=await client.waitForTransactionReceipt({hash:hash1});if(receipt1.status!=='success')throw new Error('Metadata transaction reverted');const log=receipt1.logs.map(l=>{try{return decodeEventLog({abi:registryAbi,data:l.data,topics:l.topics});}catch{return null;}}).find(x=>x?.eventName==='LaunchMetadataRegistered');if(!log||log.eventName!=='LaunchMetadataRegistered')throw new Error('Config ID event missing');const configId=log.args.configId;const launchFee=await client.readContract({address:factory,abi:factoryAbi,functionName:'launchFee'});setStatus('Simulating factory launch');const sim2=await client.simulateContract({account:address,address:factory,abi:factoryAbi,functionName:'createLaunch',args:[configId],value:launchFee});setStatus(`Approve factory launch in wallet (transaction 2 of 2; value ${launchFee} wei)`);const hash2=await wallet.writeContract(sim2.request);const receipt2=await client.waitForTransactionReceipt({hash:hash2});if(receipt2.status!=='success')throw new Error('Factory transaction reverted');setStatus(`Created config ${configId}; tx ${hash2}`);}catch(e){setStatus(e instanceof Error?e.message:'Creation failed safely');}finally{setBusy(false);}}
return <section className="space-y-4 rounded-3xl border border-white/10 bg-slate-900/60 p-6"><h2 className="text-xl font-semibold">Controlled Slice 3 test asset</h2><p>Name: {SLICE3_TEST_TOKEN.name}</p><p>Symbol: {SLICE3_TEST_TOKEN.symbol}</p><p className="text-sm text-white/60">Sepolia-only test metadata; no production branding or value claim.</p><p className="text-xs">Registry: {registry}<br/>Factory: {factory}<br/>Connected wallet: {address??'none'}</p><button onClick={create} disabled={busy||!isConnected||chainId!==11155111} className="rounded bg-indigo-500 px-4 py-2 disabled:opacity-40">Simulate and create test asset</button><NextActionHint message={chainId&&chainId!==11155111?'Switch to Sepolia explicitly before continuing':status}/></section>}
